# Generated by Django 3.0.3 on 2020-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField(null=True)),
                ('abstract', models.TextField(null=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('big_class', models.TextField(null=True)),
                ('small_class', models.TextField(null=True)),
            ],
        ),
    ]
